#%RAML 1.0
title: "Meet us"
version: v0.1.0
protocols: [ HTTP, HTTPS ]
description: !include README.md
baseUri: https://www.apis.com/meetus/v0

uses:
  places: types/places.raml
  users: types/users.raml

/places:
  description: |
    Resource used to manage all the places where the app users can meet.
  type: collection
  post:
    description: |
      This service retrieves a list of places where the app users could meet.  
    body:          
      application/json:
        examples:
          simplest:
            value: !include examples/places/post_request.json
            description: JSON input example for the simplest call POST /places
            displayName:  Basic JSON input example             
        type: users.users        
    responses:
      200:
        description: OK.
        body:          
          application/json:
            examples:
              simplest:
                value: !include examples/places/post_200.json
                description: JSON input example for the simplest call POST /places
                displayName:  Basic JSON input example             
            type: places.places            

/participants:
  description: |
    Resource used to manage the participant information.
  type: collection
  get:
    description: |
      This service retrieves a list of possibles participants in a meeting.  
    queryParameters: 
      fullName:
        type: string
        description: Full name parameter.
        example: "Jose"     
    responses:
      200:
        description: OK.
        body:          
          application/json:
            examples:
              simplest:
                value: !include examples/participants/get_200.json
                description: JSON input example for the simplest call GET /participant
                displayName:  Basic JSON input example             
            type: participant.participant[]                  